services:
  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rickmorty_db
    volumes:
      - postgres_data_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  server_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server_app
    ports:
      - "4040:4040"
    depends_on:
      - postgres_db
    environment:
      - DB_HOST=postgres_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=rickmorty_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  postgres_data_db: