export const rickyAndMortyNames = [
  "Rick Sanchez",
  "Morty Smith",
  "Summer Smith",
  "Beth Smith",
  "Jerry Smith",
  "Birdperson",
  "Mr. Meeseeks",
  "Squanchy",
  "Mr. Poopybutthole",
  "Tammy Guetermann",
  "Abradolf Lincler",
  "Evil Morty",
  "Noob-Noob",
  "Principal Vagina",
  "Scary Terry",
  "Jessica",
  "Unity",
  "Gearhead",
  "Krombopulos Michael",
  "Zeep Xanflorp",
  "Crocubot",
  "Phoenixperson",
  "Shrimply Pibbles",
  "Ants-In-My-Eyes Johnson",
  "Glootie",
  "Jaguar",
  "Pickle Rick",
  "Snuffles",
  "King Flippy Nips",
  "Tiny Rick",
  "Mr. Goldenfold",
  "Dr. Wong",
  "Doofus Rick",
  "Butter Robot",
  "Sleepy Gary",
  "Beth's Mytholog",
  "Ice-T",
  "Fart",
  "Roy",
  "Gazorpazorpfield",
  "Vance Maximus",
];